services:
  dfp-proxy-api:
    image: redteamsubnet61/rest.dfp-proxy:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
      DFP_PROXY_API_PORT: ${DFP_PROXY_API_PORT:-8000}
    env_file:
      - path: .env
        required: false
    volumes:
      - "api-logs:${DFP_PROXY_API_LOGS_DIR:-/var/log/rest.dfp-proxy}"
      - "api-data:${DFP_PROXY_API_DATA_DIR:-/var/lib/rest.dfp-proxy}"
    ports:
      - "${DFP_PROXY_API_PORT:-8000}:${DFP_PROXY_API_PORT:-8000}"
    tty: true


volumes:
  api-logs:
  api-data:
