services:
  dfp-proxy-api:
    volumes:
      - "./volumes/storage/rest.dfp-proxy/logs:${DFP_PROXY_API_LOGS_DIR:-/var/log/rest.dfp-proxy}"
      - "./volumes/storage/rest.dfp-proxy/data:${DFP_PROXY_API_DATA_DIR:-/var/lib/rest.dfp-proxy}"
      - "./scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./src:/app/rest.dfp-proxy"
      - "./volumes/.vscode-server:/home/dfp-user/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 512M
    # command: ["/bin/bash"]
    # command: ["-b", "uvicorn main:app --host=0.0.0.0 --port=${DFP_PROXY_API_PORT:-8000} --no-access-log --no-server-header --proxy-headers --forwarded-allow-ips='*' --reload --reload-include='*.yml' --reload-include='.env'"]
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:${DFP_PROXY_API_PORT:-8000}/api/v${DFP_PROXY_API_VERSION:-1}/ping"]
    #   start_period: 30s
    #   start_interval: 1s
    #   interval: 5m
    #   timeout: 5s
    #   retries: 3
