services:
  api:
    image: redteamsubnet61/rest.device-fp-gate:0.0.0-250101
    # volumes:
    #   - "api-vscode-server:/home/dfg-user/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 512M
    # command: ["/bin/bash"]
    # command: ["-b", "uvicorn main:app --host=0.0.0.0 --port=${DFG_API_PORT:-8000} --no-access-log --no-server-header --proxy-headers --forwarded-allow-ips='*'"]
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:${DFG_API_PORT:-8000}/api/v${DFG_API_VERSION:-1}/ping"]
    #   start_period: 30s
    #   start_interval: 1s
    #   interval: 5m
    #   timeout: 5s
    #   retries: 3


# volumes:
#   api-vscode-server:
